"
I store metadata for the OpenPonk-OntoUML-Transformations package. This package implements the logic, strategies, and user interfaces required to transform OntoUML ontology models into standard UML models.
"
Class {
	#name : 'ManifestOpenPonkOntoUMLTransformations',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-OntoUML-Transformations-Manifest',
	#package : 'OpenPonk-OntoUML-Transformations',
	#tag : 'Manifest'
}
